server:
  port: 8098

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

spring:
  application:
    name: student-service
    

  
management:
  security:
    enabled: false

logging:
  level:
    com.example.howtodoinjava: DEBUG


active-mq:
  broker-url: tcp://localhost:61616
  school-req-topic: school.req.topic
  school-resp-topic: school.resp.topic
  student-req-topic: student.req.topic
  student-resp-topic: student.resp.topic